version: '3'
services:

  app:
    build: ./
    volumes:
      - certs:/var/certs
      - .:/home/node/html
      - /home/node/html/node_modules
    depends_on:
      - openssl
    ports:
      - 3000:3000
    command: ['npm', 'start']

  openssl:
    image: centurylink/openssl
    volumes:
      - certs:/certs
    environment:
      - COMMON_NAME=lrncdn
      - KEY_NAME=lrndev

volumes:
  certs: